image: debian:buster-slim

stages:
    - build
    - deploy

build:
    stage: build
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - apt update && apt install -qy wget
        - wget -qO - https://github.com/getzola/zola/releases/download/v0.10.1/zola-v0.10.1-x86_64-unknown-linux-gnu.tar.gz | tar -zxvf -
        - zola build
    artifacts:
        paths:
            - public/

deploy:
    stage: deploy
    script:
        - apt-get update && apt install -qy openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - rsync -avz public/ fribyte@158.37.6.5:/home/fribyte/fribyte.no/fribyte.no