image: alpine:latest

buildanddeploy:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        ZOLA_VERSION: 0.15.3
    script:
        - apk add --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ zola
        - ./zola build
        - apk add --no-cache openssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - rsync -avz public/ fribyte@158.37.6.5:/home/fribyte/fribyte.no/fribyte.no