image: debian:buster-slim

buildanddeploy:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        ZOLA_VERSION: 0.15.3
    script:
        - apt-get update && apt install -qy wget openssh-client
        - wget -qO - https://github.com/getzola/zola/releases/download/v$ZOLA_VERSION/zola-v$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar -zxvf -
        - ./zola build
        - apt-get update && apt install -qy openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - rsync -avz public/ fribyte@158.37.6.5:/home/fribyte/fribyte.no/fribyte.no