title: friByte
email: fribyte@fribyte.no
description: >- # this means to ignore newlines until "baseurl:"
  friByte er en studentorganisasjon som leverer ulike IT-tjenester til andre
  studentorganisasjoner.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fribyte.no" # the base hostname & protocol for your site, e.g. http://example.com
lang: no

sass:
    sass_dir: assets/_sass

plugins:
  - jekyll-feed

