base_url = "https://fribyte.no"

title = "friByte"
description = "friByte er en studentorganisasjon med mål om å drive IT-drift for andre studentorganisasjoner i Bergen. Vi tilbyr rimelige web- og IT-tjenester tilpasset studentorganisasjoner."

default_language = "no"

compile_sass = true
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

minify_html = true

taxonomies = [
  { name = "categories", feed = false }
]

[markdown]
highlight_code = true

[languages.en]
build_search_index = true
# generate_feed = true
description = "friByte is a student organization with the goal of running IT operations for other student organizations in Bergen. We offer affordable web and IT services tailored to student organizations."
title = "friByte"

# Idk how to translate [extra], currently this is not working
# [languages.en.extra]
# nav = [
#   { name = "Services", path = "/en/services" },
#   { name = "Contact", path = "/en/contact" },
#   { name = "About us", path = "/en/about-us" },
# ]

# footer = [
#   { name = "Our clients", path = "/klienter/en" },
#   { name = "Become a member", path = "/bli-medlem/en" },
#   { name = "News", path = "/nyheter/en" },
# ]

# social_media = [
#   { name = "Twitter", url = "https://twitter.com/fribyte" }
# ]

[extra]
nav = [
  { name = "Tjenester", path = "/tjenester" },
  { name = "Kontakt", path = "/kontakt" },
  { name = "Om oss", path = "/om" },
]

footer = [
  { name = "Våre klienter", path = "/klienter" },
  { name = "Bli medlem", path = "/bli-medlem" },
  { name = "Nyheter", path = "/nyheter" },
]

social_media = [
  { name = "Twitter", url = "https://twitter.com/fribyte" }
]

email_general = "post@fribyte.no"
email_join = "bli-medlem@fribyte.no"
email_support = "hjelp@fribyte.no"
