base_url = "https://fribyte.no"

title = "friByte"
description = "friByte er en studentorganisasjon med mål om å drive IT-drift for andre studentorganisasjoner i Bergen. Vi tilbyr rimelige web- og IT-tjenester tilpasset studentorganisasjoner."

default_language = "no"

compile_sass = true
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

minify_html = true

taxonomies = [{ name = "categories", feed = false }]

[markdown]
highlight_code = true

external_links_target_blank = true

[translations]
bli_medlem = "Bli medlem"
ressurser = "Ressurser"
kontakt = "Kontakt"

[languages.en]
build_search_index = true
description = "friByte is a student organization with the goal of running IT operations for other student organizations in Bergen. We offer affordable web and IT services tailored to student organizations."
title = "friByte"

[languages.en.translations]
bli_medlem = "Become a member"
ressurser = "Resources"
kontakt = "Contact"


[extra]
nav = [
  { path = "@/tjenester.md", type = "page" },
  { path = "@/kontakt/index.md", type = "page" },
  { path = "@/om.md", type = "page" },
]

footer = [
  { path = "@/klienter.md", type = "page" },
  { path = "@/bli-medlem.md", type = "page" },
  { path = "@/nyheter/_index.md", type = "section" },
]

social_media = [
  { name = "Twitter", url = "https://twitter.com/fribyte" },
  { name = "Instagram", url = "https://www.instagram.com/fribyteno/" },
]

email_general = "post@fribyte.no"
email_join = "bli-medlem@fribyte.no"
email_support = "hjelp@fribyte.no"

[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = ["https://www.instagram.com", "https://instagram.com"]
